// <auto-generated />
using System;
using HometaskEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HometaskEntity.Migrations
{
    [DbContext(typeof(AirportContext))]
    [Migration("20180715073220_AddAttribute")]
    partial class AddAttribute
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HometaskEntity.DAL.Models.Aviator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirthday");

                    b.Property<int>("Experience");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Aviators");
                });

            modelBuilder.Entity("HometaskEntity.DAL.Models.Crew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("aviatorId");

                    b.HasKey("Id");

                    b.HasIndex("aviatorId");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("HometaskEntity.DAL.Models.Departure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CrewId");

                    b.Property<int>("FlightNumber");

                    b.Property<int>("PlaneId");

                    b.Property<int>("TimeOfDeparture");

                    b.HasKey("Id");

                    b.ToTable("Departures");
                });

            modelBuilder.Entity("HometaskEntity.DAL.Models.Flight", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ArrivalTime");

                    b.Property<string>("Destination")
                        .IsRequired();

                    b.Property<string>("PointOfDeparture")
                        .IsRequired();

                    b.Property<int>("TicketId");

                    b.Property<DateTime>("TimeOfDeparture");

                    b.HasKey("Number");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("HometaskEntity.DAL.Models.Plane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<int>("TimeSpan");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("HometaskEntity.DAL.Models.Stewardess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CrewId");

                    b.Property<DateTime>("DateOfBirthday");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.ToTable("Stewardesses");
                });

            modelBuilder.Entity("HometaskEntity.DAL.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FlightNumber");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("HometaskEntity.DAL.Models.TypePlane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CarryingCapacity");

                    b.Property<int>("CountOfSeats");

                    b.Property<string>("ModelOfPlane")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TypesPlane");
                });

            modelBuilder.Entity("HometaskEntity.DAL.Models.Crew", b =>
                {
                    b.HasOne("HometaskEntity.DAL.Models.Aviator", "aviator")
                        .WithMany()
                        .HasForeignKey("aviatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HometaskEntity.DAL.Models.Stewardess", b =>
                {
                    b.HasOne("HometaskEntity.DAL.Models.Crew")
                        .WithMany("stewardesses")
                        .HasForeignKey("CrewId");
                });
#pragma warning restore 612, 618
        }
    }
}
